// AUTO-GENERATED by scripts/seed-suburbs.ts at 2026-05-23T03:51:03.565Z.
// DO NOT edit by hand — re-run `pnpm seed:suburbs` to refresh.
//
// Pillar scores are derived from Melbourne open-data:
//   food + emergency  — social-indicators (CoM survey; suburbs outside CoM use SEIFA approx)
//   skills + resources — landmark density within 1500m of each centroid
//   social             — pedestrian-counter density within 1500m (SEIFA approx if no sensors)
// SEIFA scores are sourced from ABS 2021 IRSD deciles (project convention: 10 = most disadvantaged).
//
// Per-suburb provenance for this run:
//   Carlton    [real] landmarks: 7 education + 34 community-resource within 1500m; pedestrian: avg 408/hr over 100 samples; social-indicators 2023: food=26.7%, activity=52.7%
//   Fitzroy    [partial] landmarks: 2 education + 23 community-resource within 1500m; pedestrian: avg 182/hr over 100 samples; social-indicators 2023: respondent_group not present, used SEIFA approx
//   Brunswick  [partial] landmarks: 0 education + 0 community-resource within 1500m; pedestrian: no sensors in 1500m, used SEIFA approx; social-indicators 2023: respondent_group not present, used SEIFA approx
//   Footscray  [partial] landmarks: 0 education + 0 community-resource within 1500m; pedestrian: no sensors in 1500m, used SEIFA approx; social-indicators 2023: respondent_group not present, used SEIFA approx
//   Richmond   [partial] landmarks: 0 education + 0 community-resource within 1500m; pedestrian: no sensors in 1500m, used SEIFA approx; social-indicators 2023: respondent_group not present, used SEIFA approx

import type { Suburb } from '../types'

function rIndex(s: { food: number; skills: number; resources: number; social: number; emergency: number }): number {
  return Math.round((s.food + s.skills + s.resources + s.social + s.emergency) / 5)
}

const raw: Omit<Suburb, 'r_index'>[] = [
  {
    id:           'carlton',
    name:         'Carlton',
    postcode:     '3053',
    lat:          -37.7989,
    lng:          144.9669,
    seifa_score:  3,
    population:   17_330,
    scores:       { food: 27, skills: 84, resources: 95, social: 77, emergency: 53 },
    xp_total:     18_063,
    level:        6,
  },
  {
    id:           'fitzroy',
    name:         'Fitzroy',
    postcode:     '3065',
    lat:          -37.7986,
    lng:          144.9784,
    seifa_score:  4,
    population:   10_445,
    scores:       { food: 70, skills: 49, resources: 95, social: 70, emergency: 65 },
    xp_total:     19_488,
    level:        6,
  },
  {
    id:           'brunswick',
    name:         'Brunswick',
    postcode:     '3056',
    lat:          -37.7666,
    lng:          144.9614,
    seifa_score:  4,
    population:   24_473,
    scores:       { food: 70, skills: 35, resources: 35, social: 70, emergency: 65 },
    xp_total:     12_100,
    level:        4,
  },
  {
    id:           'footscray',
    name:         'Footscray',
    postcode:     '3011',
    lat:          -37.8003,
    lng:          144.8997,
    seifa_score:  8,
    population:   16_855,
    scores:       { food: 44, skills: 35, resources: 35, social: 44, emergency: 39 },
    xp_total:     6_209,
    level:        3,
  },
  {
    id:           'richmond',
    name:         'Richmond',
    postcode:     '3121',
    lat:          -37.8197,
    lng:          145.0061,
    seifa_score:  5,
    population:   28_055,
    scores:       { food: 64, skills: 35, resources: 35, social: 64, emergency: 59 },
    xp_total:     10_568,
    level:        4,
  },
]

export const MOCK_SUBURBS: Suburb[] = raw.map((s) => ({
  ...s,
  r_index: rIndex(s.scores),
}))
