-- Quests + supporting enums.
-- AI-generated by the Quest Generator agent and inserted by the service role
-- (which bypasses RLS); public read is restricted to status = 'active'.

do $$ begin
  create type quest_pillar as enum (
    'food_security', 'skill_density', 'resource_sharing',
    'social_connectivity', 'emergency_preparedness'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type quest_difficulty as enum ('easy', 'medium', 'hard');
exception when duplicate_object then null; end $$;

do $$ begin
  create type quest_status as enum ('draft', 'active', 'completed', 'expired');
exception when duplicate_object then null; end $$;

do $$ begin
  create type quest_source as enum ('ai_generated', 'resident_proposed', 'council');
exception when duplicate_object then null; end $$;

create table if not exists quests (
  id                  uuid primary key default gen_random_uuid(),
  suburb_id           uuid references suburbs(id) on delete cascade not null,
  title               text not null,
  description         text not null,
  pillar              quest_pillar not null,
  difficulty          quest_difficulty not null,
  source              quest_source default 'ai_generated',
  xp_reward           int not null,
  steps               jsonb not null default '[]',                -- [{order, description, completed}]
  participant_target  int default 3,
  status              quest_status default 'draft',
  expires_at          timestamptz,
  ai_rationale        text,
  data_snapshot       jsonb,                                       -- suburb data used at generation time
  created_at          timestamptz default now(),
  updated_at          timestamptz default now()
);

create index if not exists quests_suburb_status_idx on quests (suburb_id, status);
create index if not exists quests_pillar_idx        on quests (pillar);
create index if not exists quests_created_day_idx   on quests ((created_at::date));

alter table quests enable row level security;

create policy "public read active quests" on quests
  for select using (status = 'active');
