-- Resource matches: persisted output of the AI Matchmaker agent.

create table if not exists resource_matches (
  id            uuid primary key default gen_random_uuid(),
  resource_a    uuid references resources(id) on delete cascade,
  resource_b    uuid references resources(id) on delete cascade,
  ai_reason     text,
  intro_message text,                                    -- draft intro generated by Claude
  suburb_a      uuid references suburbs(id),
  suburb_b      uuid references suburbs(id),
  created_at    timestamptz default now(),
  unique (resource_a, resource_b)
);

create index if not exists resource_matches_a_idx on resource_matches (resource_a);
create index if not exists resource_matches_b_idx on resource_matches (resource_b);

alter table resource_matches enable row level security;

-- Only visible to the two parties whose resources matched.
create policy "read matches involving own resource" on resource_matches
  for select using (
    exists (
      select 1 from resources r
      where (r.id = resource_a or r.id = resource_b)
        and r.user_id = auth.uid()
    )
  );
